### ISSUE TITLE
[Issue] Rename "Discord Rovelstars Botlist" to "Rovel Discord List", and deprecate server stats post

### ISSUE THREAD

**Issue by ghost** [SidisLiveYT/discord-botlists#16]
You cant just use any name you want. Also are not going to support server stats post in future, please add a notice about it.

**Comment by DawnOfDedSec** [comment]
> You cant just use any name you want. Also are not going to support server stats post in future, please add a notice about it.

Thanks for Rename Update, I will surely update it sure on next update . and about deprecate server status thing , can you give me some detail like why and is their any alternative or new feature ? then i can work on it already

**Comment by DawnOfDedSec** [comment]
I fixed your issue and even opened a notice.md for your concern and thanks for informing me !
